papermoonio/tanssi-mkdocs

material-overrides/assets/stylesheets/tanssi.css, material-overrides/index-page.html, material-overrides/main.html, material-overrides/subsection-index-page.html
Included in this PR:
- Styles for cards rendering
- Support for dark and light mode in card icons
- Added disclaimer
=> Added styling and pages for section cards rendering

material-overrides/assets/stylesheets/tanssi.css
this PR is strictly formatting changes. **this doesn't apply any new css nor does it update any of the css.**
=> format the css file with prettier

material-overrides/assets/stylesheets/tanssi.css
This PR overrides the default admonition code styling, setting the tanssi color instead
=> Add code style for admonition code

material-overrides/home.html
=> update link to tanssi dapp

mkdocs.yml
Add in the created dates script to fix the created dates when the git plugin cannot find them
Goes with docs PR: https://github.com/moondance-labs/tanssi-docs/pull/49
=> Add fix created dates script

mkdocs.yml
Add redirects for the deploy and manage reorganization
Goes with: https://github.com/moondance-labs/tanssi-docs/pull/64
=> add the deploy and manage redirects

material-overrides/assets/stylesheets/termynal.css, mkdocs.yml
This PR adds termynal as a replacement for screenshots!
=> add termynal

material-overrides/assets/stylesheets/tanssi.css
=> Changes for Expandable Function Parameter Details

material-overrides/assets/stylesheets/tanssi.css, material-overrides/assets/stylesheets/termynal.css
=> run prettier on the css files

mkdocs.yml
adds redirects for https://github.com/moondance-labs/tanssi-docs/pull/96
=> Redirects for Renaming of Tutorials Page

mkdocs.yml
=> Update Copyright Year

mkdocs.yml
=> Relocate Proxy Page Redirect

material-overrides/assets/stylesheets/tanssi.css, material-overrides/partials/footer.html
=> add made with love by papermoon

material-overrides/assets/stylesheets/tanssi.css, mkdocs.yml
This PR adds styling for types. See `uint32` styling in image
=> add styling for types

LICENSE
=> Adds licence file

mkdocs.yml
Removes the single quotes around items in mkdocs.yml as they aren't needed anymore.
=> removes single quotes from items

mkdocs.yml
This PR adds redirects subsquid -> sqd, following the brand renaming
=> redirects for Subsquid renaming

material-overrides/home.html
This PR complements and continues PR#224 from `tanssi-docs` and addresses the addition of missing ALT attributes to images.
=> add ALT attribute to images

material-overrides/assets/stylesheets/tanssi.css, material-overrides/main.html, material-overrides/partials/actions.html, material-overrides/partials/content.html, material-overrides/partials/feedback.html, mkdocs.yml
I Modified the logic to display the feedback and added the "Edit this page" button below the Table of Contents (TOC) instead of at the bottom. Additionally, I added CSS styles to center these elements and maintain proper alignment throughout the page.
=> Move feedback on the TOC

.github/workflows/.github/workflows/deploy-docs.yml
This PR adapts the github action to deploy a branch in to a github pages
=> feat: github action deploy site

.github/workflows/deploy-docs.yml
The current solution only worked for the main landing page, but not for when you are in a section (icons in the dropdown don't show), because they point to a relative URL:
```
https://papermoonio.github.io/tanssi-mkdocs/builders/build/assets/images/dropdown-icons/build.webp
```
=> Absolute Paths Icons

.github/workflows/deploy-docs.yml
Reverts papermoonio/tanssi-mkdocs#60
=> Revert "Absolute Paths Icons"

material-overrides/assets/stylesheets/tanssi.css
This PR updates the following:
- Colors for mermaid diagrams
- H4 styling so that it uses default font weight (bold) and a slightly larger font size than normal
- Scrollbar color for search results
- Updates admonition backgrounds to use the default background color
I also ran prettier so a few additional changes were added as a result of that.
=> Update mermaid, h4, admonition, search result scrollbar styling

scripts/internal-links.py
This PR updates the internal links script so that it appropriately adds slashes to items that link to subsections, like `(/blah/blah#blah)` is now converted to `(/blah/blah/#blah)`
=> improve internal links script

material-overrides/assets/stylesheets/timeline-neoteroi.css
This PR introduces CSS for styling the timeline feature. For testing purposes, I created a PR https://github.com/moondance-labs/tanssi-docs/pull/257 with a dummy timeline just for demonstration. 
This is how it will look:
=> Add Styling for the Timeline Feature

material-overrides/home.html
This PR fixes a 404 in the Semrush report
=> Semrush SEO Report - May

material-overrides/assets/stylesheets/tanssi.css
This essentially sets the focus style to the same styling as the button without hover or focus and only applies special styling on hover
=> fix focus styling of llms button

redirects.json
Redirects that were omitted in the current published version
=> Adds redirects for rpc nodes

material-overrides/main.html
This PR adds logic for copy to clipboard to the AI resources page. Goes with [PR# 282 on tanssi-docs](https://github.com/moondance-labs/tanssi-docs/pull/282)
=> Adds logic for copy to clipboard

material-overrides/assets/stylesheets/tanssi.css
This PR just formats the CSS file
=> format css file
